sonar.projectKey=javc402_Inversiones
sonar.organization=javc402
sonar.host.url=https://sonarcloud.io

sonar.sources=frontend/src
sonar.tests=frontend/src
sonar.test.inclusions=frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx
sonar.exclusions=frontend/src/main.tsx,frontend/src/vite-env.d.ts,frontend/src/**/*.d.ts

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
